// Generated by CoffeeScript 1.10.0
(function() {
  var SomeClass;

  SomeClass = (function() {
    function SomeClass(initStr) {
      this.initStr = initStr;
    }

    SomeClass.prototype.get = function() {
      return this.initStr;
    };

    return SomeClass;

  })();

  module.exports = SomeClass;

}).call(this);

//# sourceMappingURL=SomeClass.js.map
