// Generated by CoffeeScript 1.9.0
(function() {
  var SomeClass2;

  SomeClass2 = (function() {
    function SomeClass2(_at_initStr) {
      this.initStr = _at_initStr;
    }

    SomeClass2.prototype.get = function() {
      return this.initStr;
    };

    return SomeClass2;

  })();

  module.exports = SomeClass2;

}).call(this);

//# sourceMappingURL=SomeClass2.js.map
