// Generated by CoffeeScript 1.10.0
(function() {
  var SomeClass2;

  SomeClass2 = (function() {
    function SomeClass2(initStr) {
      this.initStr = initStr;
    }

    SomeClass2.prototype.get = function() {
      return this.initStr;
    };

    return SomeClass2;

  })();

  module.exports = SomeClass2;

}).call(this);

//# sourceMappingURL=SomeClass2.js.map
