// Generated by CoffeeScript 1.10.0
(function() {
  var GibberishAES, cryptoLoc, deepModule;

  GibberishAES = require('../lib_static/test/gibberish-aes');

  deepModule = require('./depDeep/deepModule');

  cryptoLoc = module.exports;

  cryptoLoc.enc = function(data, key) {
    var enc;
    enc = GibberishAES.enc(data, deepModule.boothDeepAndShalow(key));
    return enc;
  };

  cryptoLoc.dec = function(data, key) {
    var dec;
    dec = GibberishAES.dec(data, deepModule.boothDeepAndShalow(key));
    return dec;
  };

}).call(this);

//# sourceMappingURL=cryptoLoc.js.map
