// Generated by CoffeeScript 1.9.0
(function() {
  var SomeClass;

  SomeClass = (function() {
    function SomeClass(_at_initStr) {
      this.initStr = _at_initStr;
    }

    SomeClass.prototype.get = function() {
      return this.initStr;
    };

    return SomeClass;

  })();

  module.exports = SomeClass;

}).call(this);

//# sourceMappingURL=SomeClass.js.map
