var that = this;
var cachedModules=[];
var getCachedModule = function(index) {
  if (cachedModules[index].builder!=null) {
    cachedModules[index].builder.call(that,cachedModules[index],cachedModules[index].exports);
    delete cachedModules[index].builder;
  }
  return cachedModules[index].exports;
};
cachedModules[7624] = {
  exports: {},
  builder: (function(module,exports) {// Generated by CoffeeScript 1.9.0
(function() {
  module.exports.theNonTrivialFunction = function(strIn) {
    return "ROOT_TEST_" + strIn;
  };

}).call(this);

//# sourceMappingURL=rootDependency.js.map
})
};
cachedModules[6804] = {
  exports: {},
  builder: (function(module,exports) {// Generated by CoffeeScript 1.9.0
(function() {
  module.exports.boothDeepAndShalow = function(strIn) {
    return "DEEP_TEST" + strIn;
  };

}).call(this);

//# sourceMappingURL=deepModule.js.map
})
};
cachedModules[4077] = {
  exports: {},
  builder: (function(module,exports) {// Generated by CoffeeScript 1.9.0
(function() {
  var GibberishAES, cryptoLoc, deepModule;

  GibberishAES = require('./lib_external/gibberish-aes');

  deepModule = getCachedModule(6804);

  cryptoLoc = module.exports;

  cryptoLoc.enc = function(data, key) {
    var enc;
    enc = GibberishAES.enc(data, deepModule.boothDeepAndShalow(key));
    return enc;
  };

  cryptoLoc.dec = function(data, key) {
    var dec;
    dec = GibberishAES.dec(data, deepModule.boothDeepAndShalow(key));
    return dec;
  };

}).call(this);

//# sourceMappingURL=cryptoLoc.js.map
})
};
cachedModules[1326] = {
  exports: {},
  builder: (function(module,exports) {// Generated by CoffeeScript 1.9.0
(function() {
  var SomeClass;

  SomeClass = (function() {
    function SomeClass(_at_initStr) {
      this.initStr = _at_initStr;
    }

    SomeClass.prototype.get = function() {
      return this.initStr;
    };

    return SomeClass;

  })();

  module.exports = SomeClass;

}).call(this);

//# sourceMappingURL=SomeClass.js.map
})
};
cachedModules[4102] = {
  exports: {},
  builder: (function(module,exports) {// Generated by CoffeeScript 1.9.0
(function() {
  var SomeClass2;

  SomeClass2 = (function() {
    function SomeClass2(_at_initStr) {
      this.initStr = _at_initStr;
    }

    SomeClass2.prototype.get = function() {
      return this.initStr;
    };

    return SomeClass2;

  })();

  module.exports = SomeClass2;

}).call(this);

//# sourceMappingURL=SomeClass2.js.map
})
};// Generated by CoffeeScript 1.9.0
(function() {
  var C, SomeClass, SomeClass2, crypto, cryptoLoc, deepModule, dynamicFileName, dynamicImport, emptyString, fun, fun2, message, r, rootDependency, shasum, sugar, _;

  fun2 = getCachedModule(7624).theNonTrivialFunction();

  fun = getCachedModule(7624).theNonTrivialFunction("blabla");

  _ = require('underscore');

  sugar = require('sugar');

  C = require('./lib_external/constants');

  cryptoLoc = getCachedModule(4077);

  rootDependency = require("./rootDependency");

  crypto = require('crypto');

  deepModule = new getCachedModule(6804);

  SomeClass = new (getCachedModule(1326))("test1");

  SomeClass2 = new getCachedModule(4102);

  if (fun !== "ROOT_TEST_blabla") {
    throw new Error("ups did not work we got: " + fun + "  instead of ROOT_TEST_blabla");
  }

  dynamicFileName = './depDynamic/filename_used_in_dynamic_require';

  if (GLOBAL._loadDynamic) {
    dynamicImport = require(dynamicFileName);
  }

  message = cryptoLoc.dec(cryptoLoc.enc(C.PART_A + C.PART_B, "secret"), "secret");

  shasum = crypto.createHash('sha1');

  r = shasum.update(message).digest("hex");

  console.log(rootDependency.theNonTrivialFunction(r));

  emptyString = "";

  if (!_.isEqual(rootDependency.theNonTrivialFunction(r), "ROOT_TEST_6af9b2faa8ae8e408decd4f7121888af71597a90")) {
    throw new Error("ups did not work we got: " + rootDependency.theNonTrivialFunction(r) + "  instead");
  }

  if (!_.isEqual(deepModule.boothDeepAndShalow(r), deepModule.boothDeepAndShalow("6af9b2faa8ae8e408decd4f7121888af71597a90"))) {
    throw new Error("ups did not work we got: " + r + "  instead");
  }

  if (!_.isEqual(SomeClass.get(), "test1")) {
    throw new Error("ups did not work we got: " + SomeClass.get() + "  instead test1 ");
  }

  if (!_.isEqual((new SomeClass2("test2").get()) + emptyString, "test2")) {
    throw new Error("ups did not work we got: " + (new SomeClass2("test2").get() + "  instead test2 "));
  }

}).call(this);

//# sourceMappingURL=main.js.map
