// Generated by CoffeeScript 1.10.0
(function() {
  module.exports.theNonTrivialFunction = function(strIn) {
    return "ROOT_TEST_" + strIn;
  };

}).call(this);

//# sourceMappingURL=rootDependency.js.map
