// Generated by CoffeeScript 1.7.1
(function() {
  var NodeUglifier, fs, packageUtils, path;

  fs = require('fs');

  NodeUglifier = require("../NodeUglifier");

  packageUtils = require('../libs/packageUtils');

  path = require('path');

  exports.testPackageUtils = function(test) {
    var shouldBeResult1, shouldBeResult2;
    test.deepEqual(packageUtils.getMatchingFiles("lib_compiled/test/testproject/main.js", []), []);
    shouldBeResult1 = ['C:\\DEV\\GITHOME\\git5\\node-uglifier\\lib_compiled\\test\\testproject\\depa\\constants.js', 'C:\\DEV\\GITHOME\\git5\\node-uglifier\\lib_compiled\\test\\testproject\\depa\\constants.map'];
    test.deepEqual(packageUtils.getMatchingFiles("lib_compiled/test/testproject/", ["./depa/"]), shouldBeResult1);
    test.deepEqual(packageUtils.getMatchingFiles("lib_compiled/test/testproject", ["./depa/"]), shouldBeResult1);
    test.deepEqual(packageUtils.getMatchingFiles("lib_compiled/test/testproject/main.js", ["./depa/"]), shouldBeResult1);
    shouldBeResult2 = ['C:\\DEV\\GITHOME\\git5\\node-uglifier\\lib_compiled\\test\\testproject\\main\\main.js', 'C:\\DEV\\GITHOME\\git5\\node-uglifier\\lib_compiled\\test\\testproject\\main\\main.map', 'C:\\DEV\\GITHOME\\git5\\node-uglifier\\lib_compiled\\test\\testproject\\depb\\cryptoLoc.js', 'C:\\DEV\\GITHOME\\git5\\node-uglifier\\lib_compiled\\test\\testproject\\depb\\depDeep\\deepModule\\deepModule.js', 'C:\\DEV\\GITHOME\\git5\\node-uglifier\\lib_compiled\\test\\testproject\\depb\\depDeep\\deepModule\\deepModule.map'];
    test.deepEqual(packageUtils.getMatchingFiles("lib_compiled/test/testproject/main.js", ["main", "./depb/cryptoLoc.js", "./depb/depDeep/deepModule"]), shouldBeResult2);
    return test.done();
  };

  exports.testMerge = function(test) {
    var me, mergedSource, nodeUglifier, testFile;
    testFile = "lib_compiled/test/resultFiles/simpleMerge.js";
    nodeUglifier = new NodeUglifier("lib_compiled/test/testproject/main.js", {
      rngSeed: "hello"
    });
    mergedSource = nodeUglifier.merge().toString();
    try {
      eval(mergedSource);
    } catch (_error) {
      me = _error;
      test.fail(me.toString(), "expected no error thrown from combined project");
    }
    test.equals(packageUtils.readFile(testFile).toString(), mergedSource);
    return test.done();
  };

  exports.testMergeWithFilter = function(test) {
    var mergedSource, nodeUglifier, testFile;
    testFile = "lib_compiled/test/resultFiles/simpleMergeWithFilter.js";
    nodeUglifier = new NodeUglifier("lib_compiled/test/testproject/main.js", {
      rngSeed: "hello",
      mergeFileFilter: ["./lib_static/test/", "./depa/constants.js"]
    });
    mergedSource = nodeUglifier.merge().toString();
    test.equals(packageUtils.readFile(testFile).toString(), mergedSource);
    return test.done();
  };

  exports.testMergeWithFilterAndUglify = function(test) {
    var mergedSource, nodeUglifier, testFile, uglifySourceMap;
    testFile = "lib_compiled/test/resultFiles/simpleMergeWithFilterAndUglify.js";
    uglifySourceMap = "lib_compiled/test/resultFiles/sourcemaps/simpleMergeWithFilterAndUglify.js";
    nodeUglifier = new NodeUglifier("lib_compiled/test/testproject/main.js", {
      rngSeed: "hello",
      mergeFileFilter: ["./lib_static/test/", "./depa/constants.js"]
    });
    mergedSource = nodeUglifier.merge().uglify().toString();
    nodeUglifier.exportSourceMaps(uglifySourceMap);
    test.equals(packageUtils.readFile(testFile).toString(), mergedSource);
    return test.done();
  };

}).call(this);

//# sourceMappingURL=unitTest.map
