// Generated by CoffeeScript 1.10.0
(function() {
  var _PART_A, _PART_B;

  _PART_A = "first part of secret";

  _PART_B = "second part of secret";

  module.exports.PART_A = _PART_A;

  module.exports.PART_B = _PART_B;

}).call(this);

//# sourceMappingURL=filename_used_in_dynamic_require.js.map
